import path from 'node:path';
import fs from 'fs-extra';
import { getCfgFolderLocation } from './define-cfg-folder-location';
import { MIRV_POV_OFFLINE_LOCKDOWN_COMMANDS } from 'csdm/node/video/hlae/mirv-pov-commands';

export const OFFLINE_RECORDING_CFG_NAME = 'csdm_offline.cfg';

export function getOfflineRecordingCfgContent() {
  return [
    '// Generated by CS Demo Manager for MIRV POV offline recording.',
    '// Do not use this client on VAC servers.',
    ...MIRV_POV_OFFLINE_LOCKDOWN_COMMANDS,
    'echo [CS:DM] Offline recording lockdown loaded',
    '',
  ].join('\n');
}

/**
 * Writes csdm_offline.cfg under the CS:DM (or custom HLAE) cfg folder so
 * `+exec csdm_offline.cfg` can disable connect aliases in-game.
 */
export async function writeOfflineRecordingCfg(cfgFolderPath?: string) {
  const folderPath = cfgFolderPath ?? path.join(getCfgFolderLocation(), 'cfg');
  await fs.ensureDir(folderPath);
  const filePath = path.join(folderPath, OFFLINE_RECORDING_CFG_NAME);
  await fs.writeFile(filePath, getOfflineRecordingCfgContent(), 'utf8');
  return filePath;
}
